version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: messageboard-backend
    volumes:
      - ./server/database:/data
    environment:
      - PORT=3001
    restart: unless-stopped
  caddy:
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    container_name: mix-forum-caddy
    restart: unless-stopped
    ports:
      - "8093:8093"
    volumes:
      - ./dist:/usr/share/caddy/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
